routes/web.php
<?php

Auth::routes();

Route::get('/home', 'HomeController@showHomePage')->name('home');
Route::get('/', 'HomeController@showHomePage')->name('home');

Route::post('/search', 'SearchController@getJsonResults')->name('search-results-json');

#Products
Route::get('/products/{filter?}', 'ProductsController@showProductsPage')->where('filter', '[a-zA-Z]+')->name('products');
Route::get('/products/{id}', 'ProductsController@showSingleProductPage')->where('id', '[0-9]+')->name('product');
Route::post('/products', 'ProductsController@getJsonProducts')->name('json-products');

#Basket
Route::get('/profile/basket', 'CartController@showCartPage')->name('profile-basket');
Route::post('/basket/sidebar', 'CartController@getCartShortInfo')->name('json-basket-sidebar');
Route::post('/basket/add', 'CartController@addProduct')->name('add-product-to-basket');
Route::post('/basket/remove', 'CartController@removeProduct')->name('remove-product-from-basket');
Route::post('/basket/count', 'CartController@getProductsCount')->name('count-products-in-basket');
Route::post('/basket/quantity/change', 'CartController@changeProductQuantity')->name('change-product-quantity-in-basket');

#Favorites
Route::post('/favorites', 'FavoritesController@getJsonFavorites')->name('json-favorites');
Route::post('/favorites/add', 'FavoritesController@addProduct')->name('add-product-to-favorites');
Route::post('/favorites/remove', 'FavoritesController@removeProduct')->name('remove-product-to-favorites');

#Orders
Route::get('/order', 'OrdersController@getOrderPage')->name('order');
Route::get('/order/accept', 'OrdersController@getOrderAcceptPage')->name('order-accept');
Route::get('/order/payment/cancel/{uid}', 'OrdersController@cancelPayment')->where('uid', '[a-zA-Z0-9]+')->name('order-cancel-payment');
Route::post('/order', 'OrdersController@makeOrder')->name('make-order');
Route::post('/order/update', 'OrdersController@updateOrder')->name('update-order');
Route::post('/order/accept', 'OrdersController@makePayment')->name('make-payment');

#Payments
Route::get('/order/paypal/{uid?}', 'OrdersController@paymentPayPalExpress')->where('uid', '[a-fA-F0-9]{7}')->name('make-order-paypal');

#Profile
Route::get('/profile', 'ProfileController@showProfilePage')->name('profile');
Route::get('/profile/favorites', 'ProfileController@showFavoritesPage')->name('profile-favorites');
Route::get('/profile/orders', 'ProfileController@showOrdersPage')->name('profile-orders');
Route::get('/profile/viewed', 'ProfileController@showLastViewedPage')->name('profile-last-viewed');
Route::post('/profile/edit', 'ProfileController@changeProfileData')->name('profile-edit');

#Message
Route::get('/message/{code}', 'MessagesController@getMessagePage')->where('code', '[0-9]+')->name('message');

#Cookies
Route::post('/cookies/accept', 'CookiesController@acceptCookies')->name('accept-cookies');

#Static pages
Route::get('/contacts', 'ContactsController@getContactsPage')->name('contacts');
Route::post('/contacts/send', 'EmailRequestsController@sendContactForm')->name('contacts-send');

Route::get('/about', 'AboutController@getAboutPage')->name('about');
Route::get('/information/privacy-policy', 'InformationController@getPolicyPage')->name('privacy-policy');
Route::get('/information/regimen', 'InformationController@getRegimenPage')->name('regimen');
Route::get('/information/delivery-and-payment', 'InformationController@getDeliveryAndPaymentPage')->name('delivery-payment');
Route::get('/information/complaints-and-returns', 'InformationController@getComplaintsAndReturnsPage')->name('complaints-returns');

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
	protected $table = 'carts';

	public function products()
	{
		return $this->belongsToMany(Product::class, 'cart_product', 'cart_id', 'product_id')
			->withPivot(['id', 'size', 'color', 'quantity', 'actual_price', 'summary']);
	}

	public static function getProductsCount()
	{
		if ($user = auth()->user()) {
			if ($cart = $user->activeCart) {
				return $cart->products->count();
			}
		} elseif ($guest_cart = session('guest_cart')) {
			return count($guest_cart);
		}

		return 0;
	}

	public static function getProductsSummaryPrice()
	{
		if ($user = auth()->user()) {
			if ($cart = $user->activeCart) {
				$summary = 0;

				foreach ($cart->products as $product) {
					$summary += $product->pivot->summary;
				}

				return $summary;
			}
		}

		return 0;
	}

	public static function isAllProductsAvailable()
	{
		if ($user = auth()->user()) {
			if ($cart = $user->activeCart) {
				$switcher = true;
				$tmp = 0;

				foreach ($cart->products as $product) {
					foreach ($cart->products()->where('products.id', '=', $product->id)->wherePivot('size', '=', $product->pivot->size)->get() as $item) {
						$tmp += $item->pivot->quantity;
					}

					if ($tmp > $product['s' . $product->pivot->size]) {
						$switcher = false;
						break;
					}
				}

				return $switcher;
			}
		}

		return false;
	}

	public function getProductsSummaryPriceAttribute()
	{
		$summary = 0;

		if (isset($this->products)) {
			foreach ($this->products as $product) {
				$summary += $product->pivot->summary;
			}
		}

		return $summary;
	}

	public function getProductsCountAttribute()
	{
		$count = 0;

		if (isset($this->products)) {
			$count = $this->products->count();
		}

		return $count;
	}
}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
	protected $table = 'orders';

	public function user()
	{
		return $this->hasOne(User::class, 'id', 'user_id');
	}

	public function cart()
	{
		return $this->hasOne(Cart::class, 'id', 'cart_id');
	}

	public static function getCountAllNewOrders()
	{
		return Order::where('order_status', 'realization')->count();
	}

	public static function getCountUserNewOrders()
	{
		if (auth()->user())
			return Order::where([
				['user_id', '=', auth()->user()->id],
				['order_status', '=', 'realization'],
			])->count();

		return 0;
	}

	public function getInitialsAttribute()
	{
		return $this->attributes['name'] . ' ' . $this->attributes['surname'];
	}

	public function getAddressAttribute()
	{
		return $this->attributes['country']
			. ', ' . $this->attributes['postal_code']
			. ' ' . $this->attributes['locality']
			. ', ' . $this->attributes['street']
			. ' ' . $this->attributes['house_number'];
	}

	public function getProductsCountAttribute()
	{
		$count = 0;
		if (isset($this->cart)) {
			$quantity = $this->cart->products()->sum('quantity');
			$count = $this->cart->products_count . ' (' . $quantity . ')';
		}

		return $count;
	}

	public function getProductsSummaryAttribute()
	{
		$summary = 0;
		if (isset($this->cart)) {
			$summary = $this->cart->products_summary_price;
		}

		return $summary;
	}

	public function getStatusAttribute()
	{
		switch ($this->attributes['order_status']) {
			case 'processing':
				$status = 'przetwarzanie';
				break;
			case 'canceled':
				$status = 'anulowane';
				break;
			case 'done':
				$status = 'gotowe';
				break;
			case 'realization':
				$status = 'realizacja';
				break;
			default:
				$status = 'none';
		}

		return $status;
	}
}

app/Product.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\File;

class Product extends Model
{
	protected $table = 'products';

	#Before removing the product - delete its images
	public function beforeDeleting()
	{
		foreach ($this->images as $image) {
			File::delete(public_path($image['link']));
		}

		$this->images()->delete();
	}

	#
	#
	#
	#--------------------------------------------------------------------

	public function images()
	{
		return $this->hasMany(ProductImage::class);
	}

	public function category()
	{
		return $this->hasOne(ProductCategory::class, 'id', 'category_id');
	}

	public function colors()
	{
		return $this->belongsToMany(ProductColor::class, 'product_color', 'product_id', 'color_id');
	}

	public function favorites()
	{
		return $this->belongsToMany(User::class, 'favorites', 'product_id', 'user_id');
	}

	#
	#
	#
	#--------------------------------------------------------------------
	public static function productsMaxPrice()
	{
		return round((1 + config('efect.surcharge.percents')) * Product::max('price') + config('efect.surcharge.fixed'), 2, PHP_ROUND_HALF_EVEN);
	}

	public static function getSpecialFilter($filter)
	{
		if (in_array($filter, ['sale', 'new'])) {
			return $filter;
		} elseif ($category = ProductCategory::where('name', '=', $filter)->first()) {
			return $category->id;
		}

		return null;
	}

	#
	#
	#
	#--------------------------------------------------------------------
	public function getUidAttribute()
	{
		return str_pad($this->attributes['id'], 6, "0", STR_PAD_LEFT);
	}

	public function getAvailabilityAttribute()
	{
		for ($i = 34; $i <= 56; $i += 2) {
			if ($this->attributes['s' . $i] > 0)
				return true;
		}

		return false;
	}

	public function getMainImageAttribute()
	{
		return $this['images']->first();
	}

	public function getPriceAttribute()
	{
		return round((1 + config('efect.surcharge.percents')) * $this->attributes['price'] + config('efect.surcharge.fixed'), 2, PHP_ROUND_HALF_EVEN);
	}

	public function getAdminPriceAttribute()
	{
		return $this->attributes['price'];
	}

	public function setAdminPriceAttribute($price)
	{
		$this->attributes['price'] = $price;
	}

	public function getOfferPriceAttribute()
	{
		$offer_price = null;

		if ($this['offer_value'] > 0) {
			switch ($this['offer_type']) {
				case 'percent':
					$offer_price = round((1 - ($this['offer_value'] / 100)) * $this['price'], 2, PHP_ROUND_HALF_EVEN);
					break;
				case 'fix_discount':
					$offer_price = round($this['price'] - $this['offer_value'], 2, PHP_ROUND_HALF_EVEN);
					break;
				case 'fix_price':
					$offer_price = round((1 + config('efect.surcharge.percents')) * $this['offer_value'] + config('efect.surcharge.fixed'), 2, PHP_ROUND_HALF_EVEN);
					break;
			}
		}

		return $offer_price;
	}

	public function getOfferValueAttribute()
	{
		if ($this->attributes['offer_value'] > 0) {
			if ($this->attributes['offer_type'] == 'percent') {
				return round($this->attributes['offer_value']);
			}

			return $this->attributes['offer_value'];
		}

		return null;
	}

	public function getProductImagesAttribute()
	{
		$images = ProductImage::where('product_id', '=', $this['id'])->select('link')->get();
		$links = [];

		foreach ($images as $image) {
			$links [] = $image['link'];
		}

		return $links;
	}

	public function setProductImagesAttribute($images)
	{
		return true;
	}

	public function getIsFavoriteAttribute()
	{
		return auth()->user() && auth()->user()->favorites->contains($this->attributes['id']) ? true : false;
	}

	#
	#
	#
	#--------------------------------------------------------------------

	public function processImages($new_images)
	{
		$p_images = ProductImage::where('product_id', '=', $this['id'])->select('link')->get();

		$old_images = [];

		foreach ($p_images as $p_image) {
			$old_images [] = $p_image['link'];
		}

		$intersect_images = array_intersect($old_images, $new_images);
		$images_to_del = array_diff($old_images, $intersect_images);

		foreach ($images_to_del as $item) {
			File::delete(public_path($item));
			ProductImage::where('link', '=', $item)->first()->delete();
		}

		$images_to_save = array_diff($new_images, $intersect_images);

		foreach ($images_to_save as $item) {
			$image = new ProductImage();
			$image['product_id'] = $this['id'];
			$image['link'] = $item;
			$image->save();
		}
	}

	public function saveViewedProducts()
	{
		$viewed = session('viewed_products') ? session('viewed_products') : collect();

		if (!$viewed->contains('id', $this->attributes['id'])) {
			$viewed->push(['id' => $this->attributes['id'], 'timestamp' => Carbon::now()->timestamp]);

			$this->attributes['views'] = $this->attributes['views'] + 1;
			$this->save();
		}

		session()->put('viewed_products', $viewed);
	}

	public function getViewedProducts($limit = 3)
	{
		$viewed = session('viewed_products') ? session('viewed_products') : collect();

		if (isset($this->attributes['id']))
			$viewed = $viewed->where('id', '!=', $this->attributes['id'])->sortByDesc('timestamp')->pluck('id');
		else
			$viewed = $viewed->sortByDesc('timestamp')->pluck('id');

		if (count($viewed) > 0) {
			return Product::where('visible', true)->whereIn('id', $viewed->reverse())->limit($limit)->inRandomOrder()->get();
		}

		return null;
	}

	public function checkSizeAvailability($size = null)
	{
		return in_array($size, config('efect.sizes')) && count($this->attributes['s' . $size]) > 0 ? $this->attributes['s' . $size] : false;
	}

	public function getAvailableSizes($return_type = 'array')
	{
		$result = [];

		if (in_array($return_type, ['array', 'string'])) {
			foreach (config('efect.sizes') as $size) {
				if ($this->attributes['s' . $size] > 0)
					array_push($result, $size);
			}

			switch ($return_type) {
				case 'string':
					$result = implode(', ', $result);
					break;
			}
		}

		return $result;
	}
}

resources/views/admin/order-info.blade.php
<link rel="stylesheet" href="{{ asset('packages/sleepingowl/styles/order.css') }}">

<div class="row">
	<div class="col-sm-6 col-md-4 col-lg-3">
		<div class="delivery-info">
			<div class="title">Dostawa:</div>
			<div class="info__item">
				<strong>Państwo: </strong>
				<span>{{ $model->country }}</span>
			</div>
			<div class="info__item">
				<strong>Miejscowość: </strong>
				<span>{{ $model->locality }}</span>
			</div>
			<div class="info__item">
				<strong>Kod pocztowy: </strong>
				<span>{{ $model->postal_code }}</span>
			</div>
			<div class="info__item">
				<strong>Ulica: </strong>
				<span>{{ $model->street . '&nbsp;' . $model->house_number }}</span>
			</div>
			<div class="info__item map-link">
				<a href="https://maps.google.com/?q={{ $model->address }}" target="_blank">
					<i class="fa fa-map-marker"></i>
					<span>Pokaż na mapie</span>
				</a>
			</div>
		</div>
	</div>
	<div class="col-sm-6 col-md-4 col-lg-3">
		<div class="client-info">
			<div class="title">Klient:</div>
			<div class="info__item">
				<strong>Imie: </strong>
				<span>{{ $model->name }}</span>
			</div>
			<div class="info__item">
				<strong>Nazwisko: </strong>
				<span>{{ $model->surname }}</span>
			</div>
			<div class="info__item">
				<strong>Email: </strong>
				<a href="mailto:{{ $model->email }}">{{ $model->email }}</a>
			</div>
			<div class="info__item">
				<strong>Telefon: </strong>
				<span>{{ $model->phone }}</span>
			</div>
		</div>
	</div>
	<div class="col-sm-12 col-md-4 col-lg-6">
		<div class="products-info">
			<div class="main-info">
				<div class="title">Informacja o zamówieniu:</div>
				<div class="info__item">
					<strong>Numer zamówienia: </strong>
					<span>#{{ $model->order_number }}</span>
				</div>
				<div class="info__item">
					<strong>Produktów: </strong>
					<span>{{ $model->cart->products_count }}</span>
				</div>
				<div class="info__item">
					<strong>Kwota zamówienia: </strong>
					<span>{{ $model->cart->products_summary_price }} zł</span>
				</div>
				<div class="info__item">
					<strong>Dostawa: </strong>
					<span>{{ $model->delivery_type }}</span>
					@if($model->delivery_price > 0)
						<span>({{ $model->delivery_price }} zł)</span>
					@endif
				</div>
				<div class="info__item">
					<strong>Status płatności: </strong>
					<span>"{{ $model->payment_status }}"</span>
				</div>
			</div>
		</div>
	</div>
</div>
<hr>

resources/views/admin/order-products.blade.php
<link rel="stylesheet" href="{{ asset('packages/sleepingowl/styles/order.css') }}">

<div class="row">
	<div class="col-md-12">
		<hr>
		<ul class="row products-list">
			@foreach($model->cart->products as $product)
				<li class="col-xs-6 col-md-4 col-lg-3 col-xlg-2 product">
					<div class="product__image">
						<a href="{{ route('product', ['id' => $product->id]) }}" target="_blank">
							<img src="{{ asset($product->main_image->link) }}" alt="{{ $product->name }}">
						</a>
					</div>
					<div class="product__name">
						<a href="{{ route('product', ['id' => $product->id]) }}">{{ $product->name }}</a>
					</div>
					<div class="product__size-color">
						<span class="color"><i style="background: {{ $product->pivot->color }};"></i></span>
						<div class="size">{{ $product->pivot->size }}</div>
					</div>
					<hr>
					<div class="product__price-quantity">
						<span class="quantity">{{ $product->pivot->quantity }} szt.</span>
						<span> &times; </span>
						<span class="price">{{ $product->pivot->actual_price }} zł.</span>
						<span> = </span>
						<span class="summary">{{ $product->pivot->summary }} zł.</span>
					</div>
					<hr>
				</li>
			@endforeach
		</ul>
	</div>
</div>