routes/web.php
<?php

Auth::routes();

Route::get('/home', 'HomeController@showHomePage')->name('home');
Route::get('/', 'HomeController@showHomePage')->name('home');

Route::post('/search', 'SearchController@getJsonResults')->name('search-results-json');

#Products
Route::get('/products/{filter?}', 'ProductsController@showProductsPage')->where('filter', '[a-zA-Z]+')->name('products');
Route::get('/products/{id}', 'ProductsController@showSingleProductPage')->where('id', '[0-9]+')->name('product');
Route::post('/products', 'ProductsController@getJsonProducts')->name('json-products');

#Basket
Route::get('/profile/basket', 'CartController@showCartPage')->name('profile-basket');
Route::post('/basket/sidebar', 'CartController@getCartShortInfo')->name('json-basket-sidebar');
Route::post('/basket/add', 'CartController@addProduct')->name('add-product-to-basket');
Route::post('/basket/remove', 'CartController@removeProduct')->name('remove-product-from-basket');
Route::post('/basket/count', 'CartController@getProductsCount')->name('count-products-in-basket');
Route::post('/basket/quantity/change', 'CartController@changeProductQuantity')->name('change-product-quantity-in-basket');

#Favorites
Route::post('/favorites', 'FavoritesController@getJsonFavorites')->name('json-favorites');
Route::post('/favorites/add', 'FavoritesController@addProduct')->name('add-product-to-favorites');
Route::post('/favorites/remove', 'FavoritesController@removeProduct')->name('remove-product-to-favorites');

#Orders
Route::get('/order', 'OrdersController@getOrderPage')->name('order');
Route::get('/order/accept', 'OrdersController@getOrderAcceptPage')->name('order-accept');
Route::get('/order/payment/cancel/{uid}', 'OrdersController@cancelPayment')->where('uid', '[a-zA-Z0-9]+')->name('order-cancel-payment');
Route::post('/order', 'OrdersController@makeOrder')->name('make-order');
Route::post('/order/update', 'OrdersController@updateOrder')->name('update-order');
Route::post('/order/accept', 'OrdersController@makePayment')->name('make-payment');

#Payments
Route::get('/order/paypal/{uid?}', 'OrdersController@paymentPayPalExpress')->where('uid', '[a-fA-F0-9]{7}')->name('make-order-paypal');

#Profile
Route::get('/profile', 'ProfileController@showProfilePage')->name('profile');
Route::get('/profile/favorites', 'ProfileController@showFavoritesPage')->name('profile-favorites');
Route::get('/profile/orders', 'ProfileController@showOrdersPage')->name('profile-orders');
Route::get('/profile/viewed', 'ProfileController@showLastViewedPage')->name('profile-last-viewed');
Route::post('/profile/edit', 'ProfileController@changeProfileData')->name('profile-edit');

#Message
Route::get('/message/{code}', 'MessagesController@getMessagePage')->where('code', '[0-9]+')->name('message');

#Cookies
Route::post('/cookies/accept', 'CookiesController@acceptCookies')->name('accept-cookies');

#Static pages
Route::get('/contacts', 'ContactsController@getContactsPage')->name('contacts');
Route::post('/contacts/send', 'EmailRequestsController@sendContactForm')->name('contacts-send');

Route::get('/about', 'AboutController@getAboutPage')->name('about');
Route::get('/information/privacy-policy', 'InformationController@getPolicyPage')->name('privacy-policy');
Route::get('/information/regimen', 'InformationController@getRegimenPage')->name('regimen');
Route::get('/information/delivery-and-payment', 'InformationController@getDeliveryAndPaymentPage')->name('delivery-payment');
Route::get('/information/complaints-and-returns', 'InformationController@getComplaintsAndReturnsPage')->name('complaints-returns');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
	protected $table = 'orders';

	public function user()
	{
		return $this->hasOne(User::class, 'id', 'user_id');
	}

	public function cart()
	{
		return $this->hasOne(Cart::class, 'id', 'cart_id');
	}

	public static function getCountAllNewOrders()
	{
		return Order::where('order_status', 'realization')->count();
	}

	public static function getCountUserNewOrders()
	{
		if (auth()->user())
			return Order::where([
				['user_id', '=', auth()->user()->id],
				['order_status', '=', 'realization'],
			])->count();

		return 0;
	}

	public function getInitialsAttribute()
	{
		return $this->attributes['name'] . ' ' . $this->attributes['surname'];
	}

	public function getAddressAttribute()
	{
		return $this->attributes['country']
			. ', ' . $this->attributes['postal_code']
			. ' ' . $this->attributes['locality']
			. ', ' . $this->attributes['street']
			. ' ' . $this->attributes['house_number'];
	}

	public function getProductsCountAttribute()
	{
		$count = 0;
		if (isset($this->cart)) {
			$quantity = $this->cart->products()->sum('quantity');
			$count = $this->cart->products_count . ' (' . $quantity . ')';
		}

		return $count;
	}

	public function getProductsSummaryAttribute()
	{
		$summary = 0;
		if (isset($this->cart)) {
			$summary = $this->cart->products_summary_price;
		}

		return $summary;
	}

	public function getStatusAttribute()
	{
		switch ($this->attributes['order_status']) {
			case 'processing':
				$status = 'przetwarzanie';
				break;
			case 'canceled':
				$status = 'anulowane';
				break;
			case 'done':
				$status = 'gotowe';
				break;
			case 'realization':
				$status = 'realizacja';
				break;
			default:
				$status = 'none';
		}

		return $status;
	}
}

app/Http/Controllers/OrdersController.php
<?php

namespace App\Http\Controllers;

use App\Cart;
use App\DeliveryItem;
use App\Order;
use App\Traits\GeneratesMessages;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Validator;
use Omnipay\Omnipay;

class OrdersController extends Controller
{
	use GeneratesMessages;

	public function __construct()
	{
		$this->middleware('auth');
	}

	private function makeOrderNumber()
	{
		$offers_today = Order::whereDate('created_at', '=', Carbon::today())->count();
		$result = Carbon::now()->timestamp;
		$result .= str_pad($offers_today, 3, "0", STR_PAD_LEFT);

		return base_convert($result, 10, 32);
	}

	private function changeProductsCount(Order $order)
	{
		if (isset($order->cart->products)) {
			foreach ($order->cart->products as $product) {
				$product['sales'] = $product['sales'] + $product->pivot->quantity;
				$product['s' . $product->pivot->size] = $product['s' . $product->pivot->size] - $product->pivot->quantity;
				$product->save();
			}
		}
	}

	private function validateOrder($data)
	{
		$validator = Validator::make($data, [
			'name'           => 'required|max:255',
			'surname'        => 'required|max:255',
			'email'          => 'required|email|max:255',
			'phone'          => 'required|max:32',
			'country'        => 'required|max:255',
			'locality'       => 'required|max:255',
			'postal_code'    => 'required|max:50',
			'street'         => 'required|max:255',
			'house_number'   => 'required|max:50',
			'privacy_policy' => 'required',
			'regimen'        => 'required',
			'payment'        => 'required',
		]);

		return $validator;
	}

	private function sendSuccessEmail(Order $order)
	{
		Mail::send('emails.order-success', ['order' => $order], function ($message) use ($order) {
			$message->from('contact@efect-moda.com', 'efect-moda.com');
			$message->to($order->email)->subject('Twoje zamówienie na efect-moda.com');
		});
	}

	private function saveOrder()
	{
		$user = auth()->user();

		if ($user && $user->activeCart && ($session_order = session('order')) && ($cart = $user->activeCart)) {

			$order = new Order();

			$order['user_id'] = $user->id;
			$order['cart_id'] = $cart->id;
			$order['order_number'] = session('order.order_number');
			$order['order_status'] = 'processing';
			$order['name'] = session('order.name');
			$order['surname'] = session('order.surname');
			$order['email'] = session('order.email');
			$order['phone'] = session('order.phone');
			$order['country'] = session('order.country');
			$order['locality'] = session('order.locality');
			$order['postal_code'] = session('order.postal_code');
			$order['street'] = session('order.street');
			$order['house_number'] = session('order.house_number');
			$order['delivery_type'] = session('order.delivery_type');
			$order['delivery_price'] = session('order.delivery_price');
			$order['payment_type'] = session('order.payment_type');
			$order['payment_status'] = 'none';

			$order->save();

			$cart->enabled = false;
			$cart->save();

			session()->put('order_in_process', session('order.order_number'));
			session()->forget('order');

			return true;
		}

		return false;
	}

	private function restoreCart($cart_id)
	{
		$user = auth()->user();

		if ($user && ($old_cart = $user->activeCart) && ($cart = Cart::find($cart_id))) {
			if ($old_cart->products->count() > 0) {
				foreach ($old_cart->products as $product) {
					$same_products = $cart->products()->where('products.id', '=', $product->id)->wherePivot('size', '=', $product->pivot->size)->get();
					$sp_quantity = 0;

					foreach ($same_products as $same_product) {
						$sp_quantity += $same_product->pivot->quantity;
					}

					if ($sp_quantity + CartController::getSameProductsQuantity($product->id, $product->pivot->size) <= $product['s' . $product->pivot->size]) {
						$old_cart->products()->attach($product->id, [
							'size'         => $product->pivot->size,
							'color'        => $product->pivot->color,
							'quantity'     => $product->pivot->quantity,
							'actual_price' => $product->offer_price ?: $product->price,
							'summary'      => ($product->offer_price ?: $product->price) * $product->pivot->quantity,
						]);
					}
				}

				$cart->enabled = true;
				$cart->save();

				$old_cart->products()->detach();
				$old_cart->delete();
			} else {
				$old_cart->delete();
				$cart->enabled = true;
				$cart->save();
			}
		}
	}

	#
	#------------------------------------------------------------------------
	#

	#GET /order
	public function getOrderPage()
	{
		$delivery_types = DeliveryItem::get();
		$user = auth()->user();

		if (Cart::getProductsCount() <= 0) {
			return $this->getMessagePage(1);
		}

//		if (!Cart::isAllProductsAvailable()) {
//			return $this->getMessagePage(6);
//		}

		if (Cart::getProductsSummaryPrice() < config('efect.free_delivery') && !$delivery_types) {
			if (auth()->user()->hasRole(['developer', 'owner']))
				return $this->getMessagePage(2);

			return $this->getMessagePage();
		}

		$data = [
			'styles'         => config('resources.auth.styles'),
			'scripts'        => config('resources.auth.scripts'),
			'user'           => $user,
			'delivery_types' => $delivery_types,
			'cart'           => $user->activeCart,
		];

		return view('pages.orders.order-add')->with($data);
	}

	#POST /order
	public function makeOrder(Request $request)
	{
		$validator = $this->validateOrder($request->all());

		if ($validator->passes()) {
			if ($request['payment'] && in_array($request['payment'], ['PayPal'])) {
				$delivery_item = false;

				if (isset($request['delivery']) && !empty($request['delivery'])) {
					$delivery = json_decode($request['delivery']);

					if (!isset($delivery->id) || !$delivery_item = DeliveryItem::find($delivery->id)) {
						return [
							'status'  => false,
							'message' => (auth()->user() && auth()->user()->hasRole(['developer']))
								? $this->getJsonMessage(trans('errors-messages.delivery_method_does_not_exist'), 'warning')
								: $this->getJsonMessage(),
						];
					}
				}

				$order = [
					'user_id'        => auth()->user()->id,
					'order_number'   => $this->makeOrderNumber(),
					'name'           => $request['name'],
					'surname'        => $request['surname'],
					'email'          => $request['email'],
					'phone'          => $request['phone'],
					'country'        => $request['country'],
					'locality'       => $request['locality'],
					'postal_code'    => $request['postal_code'],
					'street'         => $request['street'],
					'house_number'   => $request['house_number'],
					'delivery_type'  => $delivery_item ? $delivery_item->name : 'Za darmo',
					'delivery_price' => $delivery_item ? $delivery_item->price : 0,
					'payment_type'   => $request['payment'],
				];

				session()->put('order', $order);

				return [
					'status'   => true,
					'redirect' => route('order-accept'),
				];
			}

			return [
				'status'  => false,
				'message' => (auth()->user() && auth()->user()->hasRole(['developer']))
					? $this->getJsonMessage(trans('errors-messages.payment_method_does_not_exist'), 'warning')
					: $this->getJsonMessage(),
			];
		}

		return [
			'status' => false,
			'errors' => $validator->errors(),
		];
	}

	#GET /order/accept/{uid}
	public function getOrderAcceptPage()
	{
		if (session()->has('order') && $user = auth()->user()) {
			$data = [
				'styles' => config('resources.auth.styles'),
				'order'  => session('order'),
				'cart'   => $user->activeCart,
			];

			return view('pages.report')->with($data);
		}

		return $this->getMessagePage();
	}

	#POST /order/accept
	public function makePayment()
	{
		if ($this->saveOrder()) {
			$order = Order::where('order_number', '=', session('order_in_process'))->first();

			if ($order->payment_type === 'PayPal') {
				return redirect()->route('make-order-paypal');
			}

			return $this->getMessagePage();
		} //TODO error: order not saved

		return $this->getMessagePage();
	}

	#GET /order/payment/cancel/{uid}
	public function cancelPayment(Request $request, $uid)
	{
		$order = Order::where('order_number', '=', $uid)->first();
		$order->order_status = 'canceled';
		$order->payment_status = 'canceled';
		$order->save();

		$this->restoreCart($order->cart_id);

		return redirect()->route('profile-basket');
	}

	#
	#------------------------------------------------------------------------
	#

	#GET /order/paypal
	public function paymentPayPalExpress(Request $request)
	{
		if (session()->has('order_in_process') && $order = Order::where('order_number', '=', session('order_in_process'))->first()) {
			$gateway = Omnipay::create('PayPal_Express');
			$gateway->setUsername('sanek.solodovnikov.94-facilitator_api1.gmail.com');
			$gateway->setPassword('65J9SF8SVX2QYJDV');
			$gateway->setSignature('AFcWxV21C7fd0v3bYYYRCpSSRl31A8X8liG7tjU97y2UpyEUu6x-HSKJ');
			$gateway->setCurrency('PLN');
			$gateway->setTestMode(true);

			if ($request['token']) {
				$response = $gateway->completePurchase([
					'token'  => $request['token'],
					'amount' => $order->cart->products_summary_price,
				])->send();
			} else {
				$response = $gateway->purchase([
					'amount'      => $order->cart->products_summary_price,
					'returnUrl'   => route('make-order-paypal'),
					'cancelUrl'   => route('order-cancel-payment', ['uid' => $order->order_number]),
					'currency'    => 'PLN',
					'description' => 'Zamówienie na efect-moda.com',
				])->send();
			}

			if ($response->isSuccessful()) {
				$order->order_status = 'realization';
				$order->payment_status = $response->getData()['PAYMENTINFO_0_PAYMENTSTATUS'] ?: 'none';

				$order->save();

				session()->forget('order_in_process');
				$this->changeProductsCount($order);
				$this->sendSuccessEmail($order);

				return $this->getMessagePage(3, null, 'dziękujemy, ' . auth()->user()->name . '!');
			} elseif ($response->isRedirect()) {
				$response->redirect();
			} else {

resources/views/pages/orders/order-edit.blade.php
@extends('layouts.main')

@section('page')

    <div class="page-header">
        <div class="container">
            <h1>edytuj zamówienie</h1>
        </div>
    </div>

    <div id="orderpage">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-md-push-9 col-sm-4 col-sm-push-8">
                    <aside class="order-aside order-aside_loaded">
                        <header>
                            <h3>moje zamówienie</h3>
                            <span>illość produktów: {{ $order->products->count() }}</span>
                        </header>
                        <ul>
                            @foreach($order->products as $product)
                                <li><a href="{{ route('product', ['id' => $product->id]) }}">{{ $product->name }} <span>({{ $product->pivot->quantity }}
                                            )</span></a></li>
                            @Endforeach
                        </ul>
                        <footer v-cloak>
                            <dl>
                                <dt>wartość zamówienia:</dt>
                                <dd ref="orderprice"
                                    data-price="{{ $order->products_summary }}">{{ $order->products_summary }} PLN
                                </dd>
                                <br>
                                <dt>koszt przesyłki:</dt>
                                <dd>
                                    @{{ deliveryData ? deliveryData.price : '0.00' }} PLN
                                    @if($order->delivery_type == 0)
                                        <div class="hint tooltip">
                                            <span class="hint__questioned-mark">?</span>
                                            <span class="tooltip__message">Darmowa dostawa przy zakupach od {{ config('efect.free_delivery') }}
                                                zł</span>
                                        </div>
                                    @endif
                                </dd>
                                <br>
                                <dt>do zapłaty:</dt>
                                <dd class="order-aside__total">@{{ totalPrice }} PLN</dd>
                            </dl>
                        </footer>
                    </aside>
                </div>
                <div class="col-md-9 col-md-pull-3 col-sm-8 col-sm-pull-4">
                    <section class="order-form">
                        <form class="efect-form" action="{{ route('update-order') }}" method="post"
                              @submit.prevent="makeOrder('update')" :class="{'efect-form_loading': sending }">
                            {{ csrf_field() }}
                            <input type="hidden" name="order_number" value="{{ $order->order_number }}"
                                   ref="order_number">

                            <h3>dane kontaktowe</h3>
                            <div class="order-form__input-group">
                                <div class="efect-form__form-group">
                                    <div is="efect-input" class="efect-form__input" type="text" name="name"
                                         v-model="orderData.name" id="name" placeholder="imię" required="true"
                                         oldvalue="{{ $order->name }}" :error="orderErrors.name"></div>
                                </div>
                                <div class="efect-form__form-group">
                                    <div is="efect-input" class="efect-form__input" type="text" name="surname"
                                         v-model="orderData.surname" id="surname" placeholder="nazwisko" required="true"
                                         oldvalue="{{ $order->surname }}" :error="orderErrors.surname"></div>
                                </div>
                                <div class="efect-form__form-group">
                                    <div is="efect-input" class="efect-form__input" type="email" name="email"
                                         v-model="orderData.email" id="email" placeholder="email" required="true"
                                         oldvalue="{{ $order->email }}" :error="orderErrors.email"
                                         readonly="true"></div>
                                </div>
                                <div class="efect-form__form-group">
                                    <div is="efect-input" class="efect-form__input" type="text" name="phone"
                                         v-model="orderData.phone" id="phone" placeholder="telefon"
                                         oldvalue="{{ $order->phone }}" :error="orderErrors.phone"></div>
                                </div>
                            </div>

                            <h3>dane do wysyłki</h3>
                            <div class="order-form__input-group">
                                <div class="efect-form__form-group">
                                    <div is="efect-input" class="efect-form__input" type="text" name="country"
                                         v-model="orderData.country" id="country" placeholder="kraj" required="true"
                                         oldvalue="{{ $order->country }}" :error="orderErrors.country"></div>
                                </div>

                                <div class="efect-form__form-group">
                                    <div is="efect-input" class="efect-form__input" type="text" name="locality"
                                         v-model="orderData.locality" id="locality" placeholder="miejscowość"
                                         required="true"
                                         oldvalue="{{ $order->locality }}" :error="orderErrors.locality"></div>
                                </div>

                                <div class="efect-form__form-group">
                                    <div is="efect-input" class="efect-form__input" type="text" name="postal_code"
                                         v-model="orderData.postal_code" id="postal_code" placeholder="kod posztowy"
                                         required="true"
                                         oldvalue="{{ $order->postal_code }}" :error="orderErrors.postal_code"></div>
                                </div>

                                <div class="efect-form__form-group">
                                    <div is="efect-input" class="efect-form__input" type="text" name="street"
                                         v-model="orderData.street" id="street" placeholder="ulica" required="true"
                                         oldvalue="{{ $order->street }}" :error="orderErrors.street"></div>
                                </div>

                                <div class="efect-form__form-group">
                                    <div is="efect-input" class="efect-form__input" type="text" name="house_number"
                                         v-model="orderData.house_number" id="house_number" placeholder="numer domu"
                                         required="true"
                                         oldvalue="{{ $order->house_number }}" :error="orderErrors.house_number"></div>
                                </div>
                            </div>

                            <h3>dostawa</h3>
                            @if($order->delivery_price > 0)
                                <div class="order-form__checkbox-group">
                                    @foreach($delivery_types as $key => $item)
                                        @if($key % 2 == 0)
                                            <div class="order-form__checkbox-group-col">
                                                @endif
                                                <label class="checkbox efect-form__checkbox">
                                                    <input type="radio" name="delivery" v-model="orderData.delivery"
                                                           :value="JSON.stringify({ id: {{ $item->id }}, price: {{ $item->price }}})"
                                                            {{ $item->name === $order->delivery_type ? 'checked ref=chosenDelivery' : '' }}>
                                                    <span class="checkbox__marker"></span>
                                                    {{ $item->name }}: {{ $item->price }} zł
                                                </label>
                                                @if(($key + 1) % 2 == 0)
                                            </div>
                                        @endif
                                    @endforeach
                                </div>
                            @else
                                <p class="info-list__info-line">za darmo</p>
                            @endif

                            <h3>płatność</h3>
                            <div class="order-form__checkbox-group">
                                <label class="checkbox efect-form__checkbox">
                                    <input type="radio" name="payment" v-model="orderData.payment"
                                           value="PayPal" {{ $order->payment_type === 'PayPal' ? ('checked ref=chosenPayment') : '' }}>
                                    <span class="checkbox__marker"></span>
                                    PayPal
                                </label>
                            </div>

                            <footer class="order-form__footer">
                                <div class="checkbox efect-form__checkbox">
                                    <input type="checkbox" id="privacy_policy" name="privacy_policy"
                                           v-model="orderData.privacy_policy">
                                    <label for="privacy_policy" class="checkbox__marker"></label>
                                    akceptuję <a href="#" target="_blank" class="efect-form__checkbox-link">politykę
                                        prywatności</a><span
                                            class="efect-form__required-star">*</span>
                                </div>
                                <div class="checkbox efect-form__checkbox">
                                    <input type="checkbox" id="regimen" name="regimen" v-model="orderData.regimen">
                                    <label for="regimen" class="checkbox__marker"></label>
                                    akceptuję <a href="#" target="_blank"
                                                 class="efect-form__checkbox-link">regulamin</a><span
                                            class="efect-form__required-star">*</span>
                                </div>
                                <p><span class="efect-form__required-star">*</span> pola wymagane</p>
                                <div class="efect-form__buttons" v-cloak>
                                    <button class="btn" type="submit"
                                            :class="{ 'btn_disabled': (sending || uncheckedCheckboxes)}"
                                            :disabled="(sending || uncheckedCheckboxes)">dalej
                                    </button>
                                    <a href="{{ session()->has('editable_order')
                                    ? route('profile-basket')
                                    : route('order-basket-restore', ['uid' => $order->order_number]) }}">wróć do
                                        koszyka</a>
                                </div>
                            </footer>

                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>

@endsection